### PR TITLE
Fixed segfault on ubuntu by updating apr

### PR DESCRIPTION
**Pull request by gaby64**
included your changes to apr in the update

### CODE REVIEW

**Comment by micczu2** [comment]
I can confirm, on MacOS (Catalina) there was a segfault also, when trying to run app after build. This gaby64's changes fixed this.
By the way, I also needed to give exact zlib path to configure. Otherwise it gave me "not found" error.
(i.e. `./configure --prefix=/usr/local/apache2nginx --with-z=/usr/local/Cellar/zlib/1.2.11`)

**Comment by samip5** [comment]
Unfortunately, this does not appear to work on Ubuntu 18.04.4 LTS:

```
/bin/bash /usr/local/src/apache2nginx/srclib/apr/libtool --silent --mode=compile gcc -g -O2 -pthread   -DHAVE_CONFIG_H  -DLINUX -D_REENTRANT -D_GNU_SOURCE   -I/usr/local/src/apache2nginx/srclib/apr-util/include -I/usr/local/src/apache2nginx/srclib/apr-util/include/private  -I/usr/local/src/apache2nginx/srclib/apr/include    -o xml/apr_xml.lo -c xml/apr_xml.c && touch xml/apr_xml.lo
xml/apr_xml.c:35:10: fatal error: expat.h: No such file or directory
 #include <expat.h>
          ^~~~~~~~~
compilation terminated.
/usr/local/src/apache2nginx/srclib/apr-util/build/rules.mk:206: recipe for target 'xml/apr_xml.lo' failed
make[3]: *** [xml/apr_xml.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/usr/local/src/apache2nginx/srclib/apr-util'
/usr/local/src/apache2nginx/srclib/apr-util/build/rules.mk:118: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/usr/local/src/apache2nginx/srclib/apr-util'
/usr/local/src/apache2nginx/build/rules.mk:72: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/apache2nginx/srclib'
/usr/local/src/apache2nginx/build/rules.mk:72: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by samip5** [comment]
@gaby64 Could you maybe make a Docker version of this app? :)

**Comment by gaby64** [comment]
`sudo apt install libexpat1 `
